# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/mubu_login_test.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubuLoginTest(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/login")
            .get("https://mubu.com/login")
            .with_headers(
                **{
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "32f11d25-c623-42a2-9b56-29e838a40cf4",
                    "_ga": "GA1.2.303684912.1622445955",
                    "_gid": "GA1.2.204283737.1622445955",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1622445955",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "7e81ed04-6561-4783-801b-8c88e296a0f5",
                    "SESSION": "28c52d0a-2203-42e9-9c6c-fadae1c66a08",
                    "SLARDAR_WEB_ID": "5dc4cb83-13d7-4223-ac72-e29d05ca8e49",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1622558188",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("https://api2.mubu.com/v3/api/user/profile")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
                    "data-unique-id": "32f11d25-c623-42a2-9b56-29e838a40cf4",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "",
                    "x-request-id": "29aebe19-26c6-46a7-82dc-e25653da9729",
                    "version": "3.0.0.21542",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 2)
            .assert_equal("body.msg", "Login Expired")
        ),
        Step(
            RunRequest("/v3/api/user/phone_login")
            .options("https://api2.mubu.com/v3/api/user/phone_login")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/phone_login")
            .post("https://api2.mubu.com/v3/api/user/phone_login")
            .with_headers(
                **{
                    "content-length": "62",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
                    "data-unique-id": "32f11d25-c623-42a2-9b56-29e838a40cf4",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "",
                    "x-request-id": "edcc14a2-853b-4304-a3dc-3f5b830adcf2",
                    "version": "3.0.0.21542",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {"phone": "15058168264", "password": "boss@123", "callbackType": 0}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/app")
            .get("https://mubu.com/app")
            .with_headers(
                **{
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "32f11d25-c623-42a2-9b56-29e838a40cf4",
                    "_ga": "GA1.2.303684912.1622445955",
                    "_gid": "GA1.2.204283737.1622445955",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1622445955",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "7e81ed04-6561-4783-801b-8c88e296a0f5",
                    "SESSION": "28c52d0a-2203-42e9-9c6c-fadae1c66a08",
                    "_gat": "1",
                    "_gat_UA-77727571-3": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1622558207",
                    "SLARDAR_WEB_ID": "b9458641-96d6-4cfb-b96f-bceefb84d9d6",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjgyNCIsImxvZ2luVHlwZSI6Im1vYmlsZSIsImV4cCI6MTYyNTE1MDIxMSwiaWF0IjoxNjIyNTU4MjExfQ.aZhRU9yQYjiPylFoDajJtA1yXYx7JGzbxWnaFnoGTkHFZhfwl7Lr3xho6r3TbwWCmyw48nqRgzKlMBYrqpaj2w",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("https://api2.mubu.com/v3/api/user/profile")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
                    "data-unique-id": "32f11d25-c623-42a2-9b56-29e838a40cf4",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjgyNCIsImxvZ2luVHlwZSI6Im1vYmlsZSIsImV4cCI6MTYyNTE1MDIxMSwiaWF0IjoxNjIyNTU4MjExfQ.aZhRU9yQYjiPylFoDajJtA1yXYx7JGzbxWnaFnoGTkHFZhfwl7Lr3xho6r3TbwWCmyw48nqRgzKlMBYrqpaj2w",
                    "x-request-id": "f0eeda18-616b-4cd5-82c1-8839067916b7",
                    "version": "3.0.0.21542",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/star_relation/get")
            .get("https://api2.mubu.com/v3/api/list/star_relation/get")
            .with_headers(
                **{
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
                    "data-unique-id": "32f11d25-c623-42a2-9b56-29e838a40cf4",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjgyNCIsImxvZ2luVHlwZSI6Im1vYmlsZSIsImV4cCI6MTYyNTE1MDIxMSwiaWF0IjoxNjIyNTU4MjExfQ.aZhRU9yQYjiPylFoDajJtA1yXYx7JGzbxWnaFnoGTkHFZhfwl7Lr3xho6r3TbwWCmyw48nqRgzKlMBYrqpaj2w",
                    "x-request-id": "fc55987d-9a18-446d-96d4-830fe7aedf2e",
                    "version": "3.0.0.21542",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/activity/five_years/participation")
            .post("https://api2.mubu.com/v3/api/activity/five_years/participation")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
                    "data-unique-id": "32f11d25-c623-42a2-9b56-29e838a40cf4",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjgyNCIsImxvZ2luVHlwZSI6Im1vYmlsZSIsImV4cCI6MTYyNTE1MDIxMSwiaWF0IjoxNjIyNTU4MjExfQ.aZhRU9yQYjiPylFoDajJtA1yXYx7JGzbxWnaFnoGTkHFZhfwl7Lr3xho6r3TbwWCmyw48nqRgzKlMBYrqpaj2w",
                    "x-request-id": "e7b3f986-61e7-4099-a992-637988128313",
                    "version": "3.0.0.21542",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 4011)
            .assert_equal("body.msg", "unknown error")
        ),
        Step(
            RunRequest("/v3/api/list/get_all_documents_page")
            .post("https://api2.mubu.com/v3/api/list/get_all_documents_page")
            .with_headers(
                **{
                    "content-length": "12",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
                    "data-unique-id": "32f11d25-c623-42a2-9b56-29e838a40cf4",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjgyNCIsImxvZ2luVHlwZSI6Im1vYmlsZSIsImV4cCI6MTYyNTE1MDIxMSwiaWF0IjoxNjIyNTU4MjExfQ.aZhRU9yQYjiPylFoDajJtA1yXYx7JGzbxWnaFnoGTkHFZhfwl7Lr3xho6r3TbwWCmyw48nqRgzKlMBYrqpaj2w",
                    "x-request-id": "28f226c1-d117-40c8-b6d1-597555e99c67",
                    "version": "3.0.0.21542",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"start": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
            .post("https://api2.mubu.com/v3/api/message/get_message_unread")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
                    "data-unique-id": "32f11d25-c623-42a2-9b56-29e838a40cf4",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjgyNCIsImxvZ2luVHlwZSI6Im1vYmlsZSIsImV4cCI6MTYyNTE1MDIxMSwiaWF0IjoxNjIyNTU4MjExfQ.aZhRU9yQYjiPylFoDajJtA1yXYx7JGzbxWnaFnoGTkHFZhfwl7Lr3xho6r3TbwWCmyw48nqRgzKlMBYrqpaj2w",
                    "x-request-id": "8d67fc78-4889-41be-ba26-4bfbd80b02a8",
                    "version": "3.0.0.21542",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"page": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("https://api2.mubu.com/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
                    "data-unique-id": "32f11d25-c623-42a2-9b56-29e838a40cf4",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjgyNCIsImxvZ2luVHlwZSI6Im1vYmlsZSIsImV4cCI6MTYyNTE1MDIxMSwiaWF0IjoxNjIyNTU4MjExfQ.aZhRU9yQYjiPylFoDajJtA1yXYx7JGzbxWnaFnoGTkHFZhfwl7Lr3xho6r3TbwWCmyw48nqRgzKlMBYrqpaj2w",
                    "x-request-id": "c1e3ffc6-784f-4f6d-b991-91b46aeedeb8",
                    "version": "3.0.0.21542",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/advertisement/get")
            .post("https://api2.mubu.com/v3/api/advertisement/get")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
                    "data-unique-id": "32f11d25-c623-42a2-9b56-29e838a40cf4",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjgyNCIsImxvZ2luVHlwZSI6Im1vYmlsZSIsImV4cCI6MTYyNTE1MDIxMSwiaWF0IjoxNjIyNTU4MjExfQ.aZhRU9yQYjiPylFoDajJtA1yXYx7JGzbxWnaFnoGTkHFZhfwl7Lr3xho6r3TbwWCmyw48nqRgzKlMBYrqpaj2w",
                    "x-request-id": "10e4e38f-ad8c-4899-a25c-8f50e57b81e2",
                    "version": "3.0.0.21542",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
                    "data-unique-id": "32f11d25-c623-42a2-9b56-29e838a40cf4",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjgyNCIsImxvZ2luVHlwZSI6Im1vYmlsZSIsImV4cCI6MTYyNTE1MDIxMSwiaWF0IjoxNjIyNTU4MjExfQ.aZhRU9yQYjiPylFoDajJtA1yXYx7JGzbxWnaFnoGTkHFZhfwl7Lr3xho6r3TbwWCmyw48nqRgzKlMBYrqpaj2w",
                    "x-request-id": "760822d3-4e3e-4bdf-b3a8-8e7b4e00d9fd",
                    "version": "3.0.0.21542",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuLoginTest().test_start()
